### ISSUE TITLE
An error has occurred while reading the shortcut map file.

### ISSUE THREAD

**Issue by chatumao** [yo35/vcc#1]
Hi there, I'm compiled the app in Manjaro after adding #include <QPainterPath> to keyboardwidget.cpp.
But starting it throws me the error mentioned in the title. Can this be fixed somehow?

**Comment by yo35** [comment]
Hi,
I haven't work on this code for a while, I'm not sure it is still working, especially with the recent versions of Boost and Qt.

Also, I recall that the app can start only after `make install`, otherwise the external files (i.e. everything in directory `/share`) will not be found by the binary. Use `./configure --prefix=/path/to/some/test/directory` to set the install directory.

**Comment by chatumao** [comment]
Thanks, it worked. Would you consider adding #include <QPainterPath> after line 34 in keyboardwidget.cpp so the app can compile on modern machines? Seems that this is the best app out there for the purpose and it would be a pity for it to become unusable...

**Comment by yo35** [comment]
Hi,
What is the missing include in https://github.com/yo35/vcc/blob/master/src/gui/widgets/keyboardwidget.cpp ?

**Comment by chatumao** [comment]
#include <QPainterPath> was needed.

**Comment by yo35** [comment]
Not sure to understand... `#include` alone would lead to an invalid C++ file.

I let you open a pull request if you thing something needs to be added to the code.

**Comment by chatumao** [comment]
I created a pull request.

**Comment by yo35** [comment]
I've just merged it. Thank you.
